language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update --preview

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  php vendor/bin/phpunit
